import gql from "graphql-tag";

export const GetFullLocationQuery = slug => gql`
{
  getLocationWithTypes(slug: "${slug}") {
    id,
    name,
    url,
    slug,
    address,
    address_2,
    city,
    state,
    zipcode,
    phone,
    about,
    feature_unit,
    feature_access,
    feature_extras,
    feature_parking,
    feature_promotion,
    reviews_intro,
    city_information,
    business_hours,
    gate_access,
    call_center_hours,
    faqs {
      keyword,
      title,
      content
    },
    marketing_numbers {
      name,
      number,
    },
    latitude,
    longitude,
    rating,
    search_distance,
    reference_distance,
    office_located {
      id,
      is_main,
      name,
      miles_to_annex,
      reference_distance,
      address,
      address_2,
      city,
      state,
      zipcode,
      latitude,
      longitude,
      phone,
      marketing_numbers {
        name,
        number,
      },
    },
    map {
      id,
      is_main,
      name,
      miles_to_annex,
      reference_distance,
      address,
      address_2,
      city,
      state,
      zipcode,
      latitude,
      longitude,
      phone,
      marketing_numbers {
        name,
        number,
      },
    },
    min_price,
    tags,
    images {
      id,
      title,
      alternative_text,
      url,
      active,
      main,
      created_at,
      updated_at
    },
    types {
      id,
      reference_id,
      name,
      unit_id,
      unit_name,
      unit_rented,
      width,
      length,
      price,
      online_price,
      is_climate,
      is_inside,
      floor,
      image,
      total_units,
      total_occupied,
      total_vacant,
      total_reserved,
      concession_id,
      promotion_name,
      tags,
      annex {
        id,
        is_main,
        name,
        miles_to_annex,
        reference_distance,
        address,
        address_2,
        city,
        state,
        zipcode,
        latitude,
        longitude,
        phone,
        marketing_numbers {
          name,
          number,
        },
      }
    }
  }

  getLocationReviews(slug: "${slug}", limit: 25) {
    title,
    description,
    rating,
    reviewer,
    initials,
    original_date
  }
}
`;